
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Jaime Sotelo
 *         David Virtus
 *         Luis Alberto Feliz
 *         Yoel Cano
 *         Hector García
 *         Luis Guillermo Abarca
 */
public class Inicio extends javax.swing.JFrame {
    
    //conectar a la base de datos
    private Statement estado;
    private ResultSet resultadoConsulta;
    private Connection conexion;
    
    public ArrayList<Usuario> listaUsuarios = new ArrayList <Usuario>(); 
    public ArrayList<Pelicula> listaPeliculas = new ArrayList <Pelicula>(); 
    /**
     * Creates new form Inicio
     */
    
    //Empieza el inicio
    public Inicio() {
        initComponents();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conexion = DriverManager.getConnection("jdbc:mysql://127.0.0.1/videoclub", "root", "");
            estado = conexion.createStatement();
            resultadoConsulta = estado.executeQuery("Select * from usuarios");
            while(resultadoConsulta.next()){
                Usuario usu = new Usuario();
                usu.apellido = resultadoConsulta.getString(3);
                usu.dni = resultadoConsulta.getString(1);
                usu.email = resultadoConsulta.getString(5);
                usu.nombre = resultadoConsulta.getString(2);
                usu.penalizacion = resultadoConsulta.getInt(4);
                
                listaUsuarios.add(usu);
            }
        }
        catch (Exception e){
        }
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conexion = DriverManager.getConnection("jdbc:mysql://127.0.0.1/videoclub", "root", "");
            estado = conexion.createStatement();
            resultadoConsulta = estado.executeQuery("Select * from peliculas");
            
            while(resultadoConsulta.next()){
                Pelicula peli = new Pelicula();
                peli.año = resultadoConsulta.getInt(3);
                peli.clasificacion = resultadoConsulta.getDouble(7);
                peli.genero = resultadoConsulta.getString(5);
                peli.id = resultadoConsulta.getInt(1);
                peli.imdb = resultadoConsulta.getInt(6);
                peli.pais = resultadoConsulta.getString(4);
                peli.resumen = resultadoConsulta.getString(8);
                peli.titulo = resultadoConsulta.getString(2);

                   listaPeliculas.add(peli);
            }
        }
        catch (Exception e){
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Connect = new javax.swing.JButton();
        IntroducirNombre = new javax.swing.JTextField();
        IntroducirClave = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Connect.setText("jButton1");
        Connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectActionPerformed(evt);
            }
        });

        IntroducirNombre.setText("jTextField1");
        IntroducirNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntroducirNombreActionPerformed(evt);
            }
        });

        IntroducirClave.setText("IntroducirClave");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(Connect, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(IntroducirNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(209, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(252, 252, 252)
                    .addComponent(IntroducirClave, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(253, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(IntroducirNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(Connect, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(251, Short.MAX_VALUE)
                    .addComponent(IntroducirClave, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(210, 210, 210)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IntroducirNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntroducirNombreActionPerformed
        
    }//GEN-LAST:event_IntroducirNombreActionPerformed

    private void ConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectActionPerformed
         if(IntroducirNombre.getText().equals("admin") && IntroducirClave.getText().equals("admin"))
        {
            new Admin().setVisible(true);
        } else{
            boolean encontrado = false;
            int contador = 0;
            while(!encontrado && contador < listaUsuarios.size())
            {
                if(listaUsuarios.get(contador).nombre.equalsIgnoreCase(IntroducirNombre.getText()))
                {
                    encontrado = true;
                    new PerfilUsuario(listaUsuarios.get(contador)).setVisible(true);
                }
                contador++;
            }
        }
    }//GEN-LAST:event_ConnectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Connect;
    private javax.swing.JTextField IntroducirClave;
    private javax.swing.JTextField IntroducirNombre;
    // End of variables declaration//GEN-END:variables
}
